"""Build a static snapshot of the console for Cloudflare Pages.

The live app is a Python backend; Pages serves files and cannot run it. So this
freezes every read-only API response to a JSON file and rewrites the frontend to
read those instead of calling a server.

What survives: results, metrics, charts, per-stock pages with projections, the
watchlist and fund as they stood at build time.
What cannot: live prices, running a backtest, buying, and the fund trading —
all of those need the backend. They are disabled in the build rather than left
to fail silently against a server that is not there.
"""

from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

ROOT = Path(__file__).resolve().parents[1]
STATIC = ROOT / "src" / "qsm" / "web" / "static"
DIST = ROOT / "dist"

# Endpoints worth freezing, and how deep to go.
TOP_RUNS = 3
TOP_STOCKS = 500


def write_json(rel: str, payload) -> Path:
    dest = DIST / rel.lstrip("/")
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(json.dumps(payload, separators=(",", ":")))
    return dest


def snapshot(app_client) -> dict:
    """Call the app in-process and store each response as a file."""
    written, skipped = [], []

    def grab(path: str, rel: str | None = None):
        try:
            r = app_client.get(path)
            if r.status_code != 200:
                skipped.append((path, r.status_code))
                return None
            payload = r.json()
            written.append(write_json(rel or (path.split("?")[0] + ".json"), payload))
            return payload
        except Exception as exc:
            skipped.append((path, str(exc)[:60]))
            return None

    all_runs = grab("/api/runs") or []
    # Prefer the largest, most useful runs and put them first — the newest run
    # is often a small test universe, and listing runs that were never
    # snapshotted just produces 404s when the user selects one.
    def _rank(entry):
        n = entry["name"]
        return (0 if "sp500" in n else 1 if "world" in n else 2, n)

    runs = sorted(all_runs, key=_rank)[:TOP_RUNS]
    grab("/api/settings")
    grab("/api/plan")
    grab("/api/ledger")
    grab("/api/watchlist?quotes=false", "/api/watchlist.json")
    grab("/api/fund")
    grab("/api/live/status")
    grab("/api/status")
    # Added with the activity log and the nightly retrain. Without these the
    # snapshot serves a page whose Activity tab is permanently empty.
    grab("/api/activity?kind=all", "/api/activity.json")
    grab("/api/learning")

    ticker_index: dict[str, list] = {}
    usable = []
    for entry in runs:
        name = entry["name"]
        base = f"/api/runs/{name}"
        grab(f"{base}/results")
        stocks = grab(f"{base}/stocks?limit={TOP_STOCKS}&sort=rank",
                      f"{base}/stocks.json")
        grab(f"{base}/forecast")
        # Per-ticker pages for everything the snapshot lists.
        for row in (stocks or {}).get("rows", []):
            t = row["ticker"]
            grab(f"{base}/stocks/{t}?project=1", f"{base}/stocks/{t}.json")
            # The model's past calls on this name, for the accuracy overlay.
            grab(f"{base}/stocks/{t}/track", f"{base}/stocks/{t}/track.json")
            ticker_index.setdefault(t.upper(), []).append(
                {"run": name, "universe": (stocks or {}).get("universe", 0),
                 "as_of": (stocks or {}).get("as_of")})
        if not (stocks or {}).get("rows"):
            # Older runs predate ticker_panel.parquet and 409 on every stock
            # call. Listing them just gives the user a run that shows nothing.
            continue
        usable.append(entry)

        src = ROOT / "runs" / name / "report.png"
        if src.exists():
            dest = DIST / "api" / "runs" / name / "report.png"
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(src, dest)

    # Only advertise runs that produced data.
    write_json("/api/runs.json", usable)

    for t, entries in ticker_index.items():
        entries.sort(key=lambda e: -(e["universe"] or 0))
    write_json("/api/find-run.json", ticker_index)

    return {"written": len(written), "skipped": skipped,
            "runs": [r["name"] for r in usable]}


STATIC_SHIM = """
/* ── static build shim ────────────────────────────────────────────────────
   No backend here. Reads pre-built JSON instead of calling the API, and
   refuses writes rather than failing silently against a server that does not
   exist. Generated by scripts/build_static.py — do not edit by hand.        */
window.QSM_STATIC = true;

const _staticPath = (path) => {
  const [raw, query] = path.split('?');
  const qs = new URLSearchParams(query || '');
  let p = raw;
  if (p.startsWith('/api/watchlist')) p = '/api/watchlist';
  else if (p.startsWith('/api/live/quotes')) return null;      // no live prices
  else if (p.startsWith('/api/history/')) return null;         // no live history
  else if (p.startsWith('/api/find-run')) p = '/api/find-run';
  else if (/\\/stocks$/.test(p)) p = p;                        // list endpoint
  return p + '.json';
};

const _origApi = api;
api = async function (path, opts) {
  if (opts && opts.method && opts.method !== 'GET') {
    throw new Error('This is a read-only snapshot — the backend is not deployed.');
  }
  // `raw` and `qs` must be derived here — they live inside _staticPath and are
  // not in scope in this function.
  const [raw, query] = path.split('?');
  const qs = new URLSearchParams(query || '');

  const target = _staticPath(path);
  if (!target) throw new Error('Live data is not available in the static build.');
  const res = await fetch(target, { headers: { 'Accept': 'application/json' } });
  if (!res.ok) throw new Error('Not in this snapshot (' + res.status + ')');
  const data = await res.json();

  // find-run is a prebuilt ticker -> runs index in the static build.
  if (raw.startsWith('/api/find-run')) {
    const want = (qs.get('ticker') || '').toUpperCase();
    return { ticker: want, runs: data[want] || [] };
  }

  // Filtering and sorting happened server-side; do it here instead.
  if (/\\/stocks$/.test(raw) && data.rows) {
    let rows = data.rows.slice();
    const q = (qs.get('q') || '').toUpperCase();
    const pos = qs.get('position') || 'all';
    const sort = qs.get('sort') || 'rank';
    if (q) rows = rows.filter(r => r.ticker.toUpperCase().includes(q));
    if (pos === 'long') rows = rows.filter(r => r.position === 'long');
    else if (pos === 'short') rows = rows.filter(r => r.position === 'short');
    else if (pos === 'held') rows = rows.filter(r => r.position !== 'flat');
    const key = { rank: 'latest_rank', contribution: 'contribution',
                  worst: 'contribution', days_long: 'days_long',
                  days_short: 'days_short' }[sort];
    if (sort === 'ticker') rows.sort((a, b) => a.ticker.localeCompare(b.ticker));
    else if (key) rows.sort((a, b) => sort === 'worst'
      ? (a[key] ?? 0) - (b[key] ?? 0) : (b[key] ?? 0) - (a[key] ?? 0));
    const total = rows.length;
    rows = rows.slice(0, Number(qs.get('limit') || 80));
    return { ...data, rows, total_matches: total, returned: rows.length };
  }
  return data;
};

// app.js runs its boot calls at the end of the file, which is BEFORE this shim
// is appended — so those first requests go out through the unpatched api() and
// 404 against paths that only exist on the backend. Re-run them now that the
// shim is in place.
(async () => {
  for (const fn of ['loadStatus', 'loadRuns', 'loadWatchlist', 'loadLiveStatus']) {
    try { if (typeof window[fn] === 'function') await window[fn](); } catch (_) {}
    try { if (typeof eval(fn) === 'function') await eval(fn)(); } catch (_) {}
  }
  // Last word on the pill. loadStatus reads the frozen /api/live/status and
  // would otherwise leave "live feed ready" on a page where nothing is live.
  const pill = document.getElementById('env-pill');
  if (pill) { pill.textContent = 'frozen snapshot'; pill.className = 'pill warn'; }
})();

document.addEventListener('DOMContentLoaded', () => {
  const banner = document.createElement('div');
  banner.className = 'notice';
  banner.style.background = 'color-mix(in srgb, var(--accent) 10%, var(--panel))';
  banner.innerHTML = '<strong>Read-only snapshot.</strong> Built __BUILT__ from run ' +
    '<code>__RUN__</code>. Live prices, running a backtest, trading and the watchlist controls ' +
    'need the Python backend and are disabled here.';
  document.body.insertBefore(banner, document.body.children[1]);
  ['run-form', 'wl-add-btn', 'fund-start', 'fund-auto', 'sim-run', 'null-btn']
    .forEach(id => { const el = document.getElementById(id); if (el) el.disabled = true; });
  document.querySelectorAll('.wl-buy, .wl-x, #pf-clear, #fund-reset, #settings-reset')
    .forEach(el => { el.disabled = true; el.title = 'Not available in the static snapshot'; });
});
"""


def write_frontend() -> None:
    """Rebuild only index.html / app.js / styles.css, leaving the snapshot alone."""
    import datetime as dt

    for name in ("styles.css", "app.js"):
        shutil.copy2(STATIC / name, DIST / name)

    html = (STATIC / "index.html").read_text()
    html = html.replace('"/static/', '"./').replace("'/static/", "'./")
    assert "/static/" not in html, "unrewritten /static/ reference remains"
    (DIST / "index.html").write_text(html)

    runs_file = DIST / "api" / "runs.json"
    first = "none"
    if runs_file.exists():
        try:
            first = json.loads(runs_file.read_text())[0]["name"]
        except Exception:
            pass
    shim = (STATIC_SHIM
            .replace("__BUILT__", dt.datetime.now().strftime("%d %b %Y %H:%M"))
            .replace("__RUN__", first))
    (DIST / "app.js").write_text((DIST / "app.js").read_text() + "\n" + shim)

    (DIST / "_headers").write_text(
        "/api/*\n  Content-Type: application/json\n  Cache-Control: max-age=300\n")
    (DIST / "_redirects").write_text("# no SPA fallback: unknown paths should 404\n")


def main():
    from fastapi.testclient import TestClient

    from qsm.web.app import app

    if DIST.exists():
        shutil.rmtree(DIST)
    DIST.mkdir(parents=True)

    client = TestClient(app)
    result = snapshot(client)

    write_frontend()

    print(f"  files written : {result['written']} JSON responses")
    print(f"  runs included : {', '.join(result['runs']) or 'none'}")
    if result["skipped"]:
        print(f"  skipped       : {len(result['skipped'])}")
        for path, why in result["skipped"][:6]:
            print(f"      {path}  ->  {why}")
    size = sum(f.stat().st_size for f in DIST.rglob("*") if f.is_file())
    print(f"  dist size     : {size / 1e6:.1f} MB")


if __name__ == "__main__":
    if "--frontend-only" in sys.argv:
        write_frontend()
        print("rebuilt index.html, app.js, styles.css (snapshot untouched)")
    else:
        main()
